---
title: "Resumo dos projetos"
author: "Marjorie Hoegen"
date: "28 de junho de 2018"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introdução

Essa página apresenta um resumo dos projetos realizado na disciplina **"Análise de Dados e Introdução à Machine Learning"**.

***

## Projeto 1

* Título: Análise Exploratória de Dados

### Descrição
Esse projeto tem como objetivo realizar uma análise exploratória dos dados **storms** do package *dplyr*

### Relatório do Projeto

Link no [meu Github](<https://github.com/marjoriehoegen) *Pages*: [Projeto 1](projetos/relatorio1.html)

***

## Projeto 2

* Título: Regressão linear

### Descrição
Esse projeto tem como objetivo realizar a previsão do preço de imóveis usando um modelo de regressão linear gerando um gráfico de resíduos

### Relatório do Projeto

Link no [meu Github](<https://github.com/marjoriehoegen>) *Pages*: [Projeto 2](projetos/relatorio2.html)

## Projeto 3

* Título: Estudo de caso BlueSky

### Descrição
O objetivo do projeto é definir o nível de proteção ideal de proteção de assentos de tarifa cheia de um companhia aérea.

### Relatório do Projeto

Link no [meu Github](<https://github.com/marjoriehoegen>) *Pages*: [Projeto 3](projetos/relatorio3.html)

## Projeto 4

* Título: Decision Tree

### Descrição
O objetivo desse projeto é fazer a previsão do nascimento de recém-nascidos abaixo do peso usando um modelo de árvore de decisão.

### Relatório do Projeto

Link no [meu Github](<https://github.com/marjoriehoegen>) *Pages*: [Projeto 4](projetos/relatorio4.html)

## Projeto 5

* Título: Regressão Logística

### Descrição
O objetivo desse projeto é fazer a previsão do nascimento de recém-nascidos abaixo do peso usando regressão logística.

### Relatório do Projeto

Link no [meu Github](<https://github.com/marjoriehoegen>) *Pages*: [Projeto 5](projetos/relatorio5.html)